apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "optimize-live.fullname" . }}-docker
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
  namespace: {{ include "optimize-live.namespace" . }}
data:
  .dockerconfigjson: {{ include "optimize-live.dockerConfig" . }}
