apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8c.collection.enabled: "true"
  name: scrape-tsdb-pods
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    any: true
  endpoints:
    - path: /recommendations
      targetPort: 8080
  selector:
    matchLabels:
      component: tsdb