apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "optimize-live.fullname" . }}
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
  namespace: {{ include "optimize-live.namespace" . }}
data:
  STORMFORGE_AUTHORIZATION_CLIENT_ID: {{ .Values.authorization.clientID | b64enc }}
  STORMFORGE_AUTHORIZATION_CLIENT_SECRET: {{ .Values.authorization.clientSecret | b64enc }}
  STORMFORGE_SERVER_IDENTIFIER: {{ .Values.stormforge.address | b64enc }}
  STORMFORGE_SERVER_ISSUER: {{ .Values.authorization.issuer | b64enc }}
  {{- range .Values.extraEnvVars }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
