{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "optimize-live.serviceAccountName" . }}
  namespace: {{ include "optimize-live.namespace" . }}
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
- name: {{ include "optimize-live.fullname" . }}-docker
{{- end }}
