apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: allow-kaas-monitoring-to-tsdb
  namespace: {{ .Values.defaultNamespace }}
spec:
  selector: component == 'tsdb'
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      metadata:
        annotations:
          from: prometheus
          to: tsdb
      protocol: TCP
      source:
        selector: app == 'prometheus'
        namespaceSelector: name=='kaas-monitoring'
      destination:
        ports:
          - 8080
    - action: Allow
      metadata:
        annotations:
          from: prometheus
          to: tsdb
      protocol: TCP
      source:
        selector: app == 'prometheus'
        namespaceSelector: name=='kaas-metrics'
      destination:
        ports:
          - 8080
    - action: Allow
      metadata:
        annotations:
          from: grafana
          to: tsdb
      protocol: TCP
      source:
        selector: component == 'grafana'
        namespaceSelector: name=='stormforge-system'
    - action: Allow
      destination:
        ports:
        - 8080
      metadata:
        annotations:
          from: recommender
          to: tsdb
      protocol: TCP
      source:
        selector: component == 'recommender'
  egress:
    - action: Allow
